import { Helmet } from 'react-helmet-async';
import React, { useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import WhySolastraSection from '../components/sections/WhySolastraSection';
import { Zap, AppWindow, Building2, ShieldCheck, CheckCircle2 } from 'lucide-react';

const applications = [
    {
        id: 'Transparent',
        title: 'Transparent PV Glass',
        desc: 'Laminated glass that can generate energy and be used in fixed windows & facades. As the transparency of the glass goes higher, the power generated by it lowers.',
        image: 'https://plus.unsplash.com/premium_photo-1663091707200-7e00b70052b6?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: 'PV Glass',
        yield: 92,
        specs: {
            Customization_Options: 'Transparency, shape, size/dimensions, junction box placement, and colour tint can be customized as per requirements.',
            Available_Technologies: 'Monocrystalline , CdTe',
            durability: 'High-Impact Safety Glass',
            warranty: '25 Years Power Output',
            compliance: 'IEC 61215, ISO 9001',
        }
    },
    {
        id: 'Opaque',
        title: 'Opaque PV Glass',
        desc: 'Rectangular opaque curtain wall glass that can generate energy. Can be customized with any color, texture/pattern, and custom image. Lighter colours decrease energy generation. Junction box & wiring can either go from the sides or from the back of the panels.',
        image: 'https://plus.unsplash.com/premium_photo-1663040280358-a7dd48ebd191?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: 'PV Glass',
        yield: 78,
        specs: {
            Customization_Options: 'Colour/pattern/image, junction box placement, shape & size can be customized.',
            transmittance: 'Semi-Transparent (30%)',
            durability: 'Double Glazed Tempered',
            warranty: '20 Years Product Warranty',
            compliance: 'EN 12600 Safety Standard',
        }
    },
    {
        id: 'Crystalline',
        title: 'Crystalline PV Glass',
        desc: 'Monocrystalline PV square cells are integrated as a 2D grid & sandwiched between layers of glass. Transparency is changed by changing the number & size of the crystalline cells. Cells can be placed as per any custom pattern needed.',
        image: 'https://plus.unsplash.com/premium_photo-1682148214992-728f78067d60?q=80&w=872&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: 'PV Glass',
        yield: 85,
        specs: {
            Available_Technologies: 'Monocrystalline',
            Customization_Options: 'Transparency, colour tint, and cell patterning can be customized.',
            durability: 'Heat-Strengthened Laminated',
            warranty: '25 Years Performance',
            compliance: 'ASTM E2190 Insulating Glass',
        }
    },
    {
        id: 'PV Walkable',
        title: 'PV Walkable Tiles',
        desc: 'Bricks used for footpaths that can generate solar energy. Coefficient of friction depends on the micro-patterns developed on the front of the tile. Tiles are pasted on footpath bricks & the wiring goes from the back of the tiles.',
        image: 'https://plus.unsplash.com/premium_photo-1678743133487-d501f3b0696b?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: 'Tiles',
        yield: 65,
        specs: {
            Customization_Options: 'Size, shape, light transmission, weight, coefficient of friction, and colour/tint.',
            Available_Technology: 'Monocrystalline',
            durability: 'Safety Laminated Railing Grade',
            warranty: '15 Years Product Warranty',
            compliance: 'EN 12600 Impact Rating',
        }
    },
    {
        id: 'Thin-Film',
        title: 'Thin-Film PV Flex',
        desc: 'Solar flexes that can be mechanically incorporated on curved structures. This can be customized by size as per requirement.',
        image: 'https://plus.unsplash.com/premium_photo-1664299621284-6aaffe67a20c?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: 'Flex',
        yield: 95,
        specs: {
            output: '210 W/m²',
            transmittance: 'Opaque Textured',
            durability: 'Class 4 Hail Impact Rated',
            warranty: '30 Years Linear Output',
            compliance: 'UL 1703 Fire Certified',
        }
    },
    {
        id: 'Solar Panels',
        title: 'Solar Panels',
        desc: 'Regular solar panels with a sturdy frame can be used as an opaque façade, curtain wall, or a spandrel. This can be customized by size as per requirement.',
        image: 'https://plus.unsplash.com/premium_photo-1678743133482-2285d3f7bc0f?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        category: 'Solar Panels',
        yield: 70,
        specs: {
            output: '95 W/m²',
            transmittance: 'Clear Vision (45%)',
            durability: 'Sound Insulation Low-E Double Panel',
            warranty: '20 Years Structural Integrity',
            compliance: 'ASHRAE 90.1 Compliant',
        }
    },
];

const Products = () => {
    const bgRef = useRef(null);

    useEffect(() => {
        let frameId;
        
        const handleScroll = () => {
            frameId = requestAnimationFrame(() => {
                if (bgRef.current) {
                    const offset = window.scrollY;
                    bgRef.current.style.transform = `translateY(${offset * 0.4}px)`;
                }
            });
        };

        window.addEventListener('scroll', handleScroll, { passive: true });
        
        return () => {
            window.removeEventListener('scroll', handleScroll);
            if (frameId) {
                cancelAnimationFrame(frameId);
            }
        };
    }, []);

    const getCategoryIcon = (category) => {
        switch(category) {
            case 'PV Glass': return AppWindow;
            case 'Tiles': return Building2;
            case 'Flex': return Zap;
            case 'Solar Panels': return ShieldCheck;
            default: return AppWindow;
        }
    };

    return (
        <div className="flex flex-col flex-1 bg-background overflow-hidden">
            <Helmet>
                <title>Products – Solastra BIPV</title>
                <meta name="description" content="Explore Solastra's range of building-integrated photovoltaic products, from solar facades to glass and roofs." />
            </Helmet>

            {/* Hero Section */}
            <section className="relative h-[400px] md:h-[500px] w-full flex items-center justify-center overflow-hidden">
                <div
                    ref={bgRef}
                    className="absolute left-0 right-0 w-full"
                    style={{
                        height: '130%',
                        top: '-15%',
                        backgroundImage: 'url("https://images.unsplash.com/photo-1508514177221-188b1c77eca2?q=80&w=1632&auto=format&fit=crop")',
                        backgroundPosition: 'center',
                        backgroundSize: 'cover',
                        backgroundRepeat: 'no-repeat',
                        willChange: 'transform'
                    }}
                />
                
                {/* Dark Overlay */}
                <div className="absolute inset-0 bg-gradient-to-r from-slate-900/90 via-slate-900/60 to-slate-900/30" />

                {/* Content */}
                <div className="relative z-10 text-center px-4 mt-16">
                    <h1 className="text-5xl md:text-6xl font-black text-white tracking-tight mb-4 drop-shadow-md">
                        Our Products
                    </h1>
                    <div className="flex items-center justify-center gap-2 text-white/90 text-sm md:text-base font-medium">
                        <Link to="/" className="hover:text-secondary transition-colors">Home</Link>
                        <span className="text-white/50">/</span>
                        <span>Products</span>
                    </div>
                </div>
            </section>

            {/* Custom Product Catalog Layout (Alternating Panels) */}
            <section className="py-12 sm:py-16 bg-white dark:bg-[#070e17] relative z-10">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">
                    
                    <div className="text-center max-w-3xl mx-auto mb-12 sm:mb-16">
                        <div className="inline-flex items-center gap-3 px-4 py-1.5 rounded-full bg-secondary/10 dark:bg-secondary/20 border border-secondary/20 mb-6 shadow-sm backdrop-blur-md">
                            <span className="w-2 h-2 rounded-full bg-secondary animate-pulse" />
                            <span className="text-secondary font-bold tracking-widest uppercase text-xs">
                                Product Catalog
                            </span>
                        </div>
                        <h2 className="text-4xl sm:text-5xl lg:text-6xl font-black text-primary dark:text-white leading-[1.1] tracking-tight mb-6">
                            Explore Our Solar <br className="hidden sm:block"/>
                            <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-amber-500 drop-shadow-sm">Product Line</span>
                        </h2>
                        <p className="text-lg sm:text-xl text-slate-600 dark:text-slate-400 font-medium leading-relaxed">
                            Discover the technical specifications and architectural applications of our premium BIPV solutions.
                        </p>
                    </div>

                    <div className="space-y-20 sm:space-y-24">
                        {applications.map((app, index) => {
                            const isEven = index % 2 === 0;
                            const Icon = getCategoryIcon(app.category);
                            return (
                                <div key={app.id} className={`flex flex-col lg:flex-row gap-8 lg:gap-12 items-center ${isEven ? '' : 'lg:flex-row-reverse'}`}>
                                    {/* Image Column */}
                                    <div className="w-full lg:w-1/2">
                                        <div className="relative aspect-[4/3] rounded-[2.5rem] overflow-hidden shadow-2xl group border border-slate-200/50 dark:border-white/10">
                                            <div className="absolute inset-0 bg-secondary/10 opacity-0 group-hover:opacity-100 transition-opacity duration-700 z-10 pointer-events-none mix-blend-overlay" />
                                            <div className="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent z-10 pointer-events-none" />
                                            
                                            <img src={app.image} alt={app.title} loading="lazy" className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105" />
                                            
                                            <div className="absolute top-6 left-6 z-20">
                                                <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/95 dark:bg-slate-950/95 backdrop-blur-md text-[10px] sm:text-xs font-bold uppercase tracking-widest text-primary dark:text-white shadow-lg border border-white/20">
                                                    <Icon size={14} className="text-secondary" />
                                                    {app.category}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    {/* Content Column */}
                                    <div className="w-full lg:w-1/2 flex flex-col justify-center">
                                        <div className="flex flex-wrap items-center gap-4 mb-5">
                                            <h3 className="text-3xl sm:text-4xl lg:text-5xl font-black text-primary dark:text-white leading-tight tracking-tight">
                                                {app.title}
                                            </h3>
                                        </div>
                                        
                                        <p className="text-slate-600 dark:text-slate-400 text-base sm:text-lg leading-relaxed mb-10 font-medium">
                                            {app.desc}
                                        </p>

                                        {/* Specs Grid directly on page */}
                                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                            {Object.entries(app.specs).map(([key, val]) => {
                                                if(key === 'compliance') return null;
                                                return (
                                                    <div key={key} className="bg-slate-50 dark:bg-white/5 p-5 rounded-2xl border border-slate-200/60 dark:border-white/5 hover:border-secondary/30 dark:hover:border-secondary/40 hover:bg-white dark:hover:bg-white/10 transition-all duration-300 group/spec">
                                                        <h4 className="text-[10px] sm:text-xs uppercase tracking-widest font-bold text-slate-400 dark:text-slate-500 mb-2 group-hover/spec:text-secondary transition-colors">
                                                            {key.replace(/_/g, ' ')}
                                                        </h4>
                                                        <p className="text-sm sm:text-base font-black text-primary dark:text-white leading-snug">
                                                            {val}
                                                        </p>
                                                    </div>
                                                );
                                            })}
                                        </div>
                                        
                                        <div className="mt-10 pt-6 border-t border-slate-200 dark:border-white/10 flex items-center gap-3">
                                            <CheckCircle2 size={18} className="text-secondary" />
                                            <span className="text-xs sm:text-sm font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                                                {app.specs.compliance}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            </section>

            {/* Why Solastra Section */}
            <WhySolastraSection />
        </div>
    );
};

export default Products;
