import { Helmet } from 'react-helmet-async';
import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import WhyKonaraSection from '../components/sections/WhyKonaraSection';
import { Zap, AppWindow, Building2, ShieldCheck, CheckCircle2, LayoutGrid, List } from 'lucide-react';


const applications = [
    {
        id: 'Transparent',
        title: 'Transparent PV Glass',
        desc: 'Laminated glass that can generate energy and be used in fixed windows & facades. As the transparency of the glass goes higher, the power generated by it lowers.',
        image: '/images/transparent-pv-glass.jpg',
        category: 'PV Glass',
        yield: 92,
        specs: {
            Customization_Options: 'Transparency, shape, size/dimensions, junction box placement, and colour tint can be customized as per requirements.',
            Available_Technologies: 'Monocrystalline , CdTe',
            durability: 'High-Impact Safety Glass',
            warranty: '25 Years Power Output',
            compliance: 'IEC 61215, ISO 9001',
        }
    },
    {
        id: 'Opaque',
        title: 'Opaque PV Glass',
        desc: 'Rectangular opaque curtain wall glass that can generate energy. Can be customized with any color, texture/pattern, and custom image. Lighter colours decrease energy generation. Junction box & wiring can either go from the sides or from the back of the panels.',
        image: '/images/opaque-pv-glass.jpg',
        category: 'PV Glass',
        yield: 78,
        specs: {
            Customization_Options: 'Colour/pattern/image, junction box placement, shape & size can be customized.',
            transmittance: 'Semi-Transparent (30%)',
            durability: 'Double Glazed Tempered',
            warranty: '20 Years Product Warranty',
            compliance: 'EN 12600 Safety Standard',
        }
    },
    {
        id: 'Crystalline',
        title: 'Crystalline PV Glass',
        desc: 'Monocrystalline PV square cells are integrated as a 2D grid & sandwiched between layers of glass. Transparency is changed by changing the number & size of the crystalline cells. Cells can be placed as per any custom pattern needed.',
        image: '/images/crystalline-pv-glass.jpg',
        category: 'PV Glass',
        yield: 85,
        specs: {
            Available_Technologies: 'Monocrystalline',
            Customization_Options: 'Transparency, colour tint, and cell patterning can be customized.',
            durability: 'Heat-Strengthened Laminated',
            warranty: '25 Years Performance',
            compliance: 'ASTM E2190 Insulating Glass',
        }
    },
    {
        id: 'PV Walkable',
        title: 'PV Walkable Tiles',
        desc: 'Bricks used for footpaths that can generate solar energy. Coefficient of friction depends on the micro-patterns developed on the front of the tile. Tiles are pasted on footpath bricks & the wiring goes from the back of the tiles.',
        image: '/images/pv-walkable-tiles-2.jpg',
        category: 'Tiles',
        yield: 65,
        specs: {
            Customization_Options: 'Size, shape, light transmission, weight, coefficient of friction, and colour/tint.',
            Available_Technology: 'Monocrystalline',
            durability: 'Safety Laminated Railing Grade',
            warranty: '15 Years Product Warranty',
            compliance: 'EN 12600 Impact Rating',
        }
    },
    {
        id: 'Thin-Film',
        title: 'Thin-Film PV Flex',
        desc: 'Solar flexes that can be mechanically incorporated on curved structures. This can be customized by size as per requirement.',
        image: '/images/thin-film-pv-flex.jpg',
        category: 'Flex',
        yield: 95,
        specs: {
            output: '210 W/m²',
            transmittance: 'Opaque Textured',
            durability: 'Class 4 Hail Impact Rated',
            warranty: '30 Years Linear Output',
            compliance: 'UL 1703 Fire Certified',
        }
    },
    {
        id: 'Solar Panels',
        title: 'Solar Panels',
        desc: 'Regular solar panels with a sturdy frame can be used as an opaque façade, curtain wall, or a spandrel. This can be customized by size as per requirement.',
        image: '/images/solar-panels.jpg',
        category: 'Solar Panels',
        yield: 70,
        specs: {
            output: '95 W/m²',
            transmittance: 'Clear Vision (45%)',
            durability: 'Sound Insulation Low-E Double Panel',
            warranty: '20 Years Structural Integrity',
            compliance: 'ASHRAE 90.1 Compliant',
        }
    },
];

const Products = () => {
    const bgRef = useRef(null);
    const [viewMode, setViewMode] = useState('card');

    useEffect(() => {
        let frameId;

        const handleScroll = () => {
            frameId = requestAnimationFrame(() => {
                if (bgRef.current) {
                    const offset = window.scrollY;
                    bgRef.current.style.transform = `translateY(${offset * 0.4}px)`;
                }
            });
        };

        window.addEventListener('scroll', handleScroll, { passive: true });

        return () => {
            window.removeEventListener('scroll', handleScroll);
            if (frameId) {
                cancelAnimationFrame(frameId);
            }
        };
    }, []);

    const getCategoryIcon = (category) => {
        switch (category) {
            case 'PV Glass': return AppWindow;
            case 'Tiles': return Building2;
            case 'Flex': return Zap;
            case 'Solar Panels': return ShieldCheck;
            default: return AppWindow;
        }
    };

    return (
        <div className="flex flex-col flex-1 bg-background overflow-hidden">
            <Helmet>
                <title>Products – Konara BIPV</title>
                <meta name="description" content="Explore Konara's range of building-integrated photovoltaic products, from solar facades to glass and roofs." />
            </Helmet>

            {/* Hero Section */}
            <section className="relative h-[400px] md:h-[500px] w-full flex items-center justify-center overflow-hidden">
                <div
                    ref={bgRef}
                    className="absolute left-0 right-0 w-full"
                    style={{
                        height: '130%',
                        top: '-15%',
                        backgroundImage: 'url("/images/builder-friendly-solar-panels.jpg")',
                        backgroundPosition: 'center',
                        backgroundSize: 'cover',
                        backgroundRepeat: 'no-repeat',
                        willChange: 'transform'
                    }}
                />

                {/* Dark/Light Overlay */}
                <div className="absolute inset-0 bg-gradient-to-r from-white/95 via-white/80 to-white/50 dark:from-slate-900/90 dark:via-slate-900/60 dark:to-slate-900/30" />

                {/* Content */}
                <div className="relative z-10 text-center px-4 mt-16">
                    <h1 className="text-5xl md:text-6xl font-black text-slate-900 dark:text-white tracking-tight mb-4 drop-shadow-md">
                        Our Products
                    </h1>
                    <div className="flex items-center justify-center gap-2 text-slate-700 dark:text-white/90 text-sm md:text-base font-bold">
                        <Link to="/" className="hover:text-primary dark:hover:text-secondary transition-colors">Home</Link>
                        <span className="text-slate-400 dark:text-white/50">/</span>
                        <span>Products</span>
                    </div>
                </div>
            </section>

            {/* Custom Product Catalog Layout */}
            <section className="py-12 sm:py-16 bg-white dark:bg-[#070e17] relative z-10 overflow-hidden min-h-screen">
                <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">

                    <div className="text-center max-w-3xl mx-auto mb-12 sm:mb-16">
                        <div className="inline-flex items-center gap-3 px-4 py-1.5 rounded-full bg-secondary/10 dark:bg-secondary/20 border border-secondary/20 mb-6 shadow-sm backdrop-blur-md">
                            <span className="w-2 h-2 rounded-full bg-secondary animate-pulse" />
                            <span className="text-secondary font-bold tracking-widest uppercase text-xs">
                                Product Catalog
                            </span>
                        </div>
                        <h2 className="text-4xl sm:text-5xl lg:text-6xl font-black text-primary dark:text-white leading-[1.1] tracking-tight mb-6">
                            Explore Our Solar <br className="hidden sm:block" />
                            <span className="text-transparent bg-clip-text bg-gradient-to-r from-secondary to-amber-500 drop-shadow-sm">Product Line</span>
                        </h2>
                        <p className="text-lg sm:text-xl text-slate-600 dark:text-slate-400 font-medium leading-relaxed">
                            Discover the technical specifications and architectural applications of our premium BIPV solutions.
                        </p>

                        {/* View Toggle */}
                        <div className="mt-8 flex justify-center">
                            <div className="inline-flex items-center bg-slate-100 dark:bg-slate-800/80 p-1.5 rounded-xl border border-slate-200 dark:border-white/10 shadow-sm">
                                <button 
                                    onClick={() => setViewMode('card')} 
                                    className={`flex items-center gap-2.5 px-6 py-2.5 rounded-lg text-sm font-bold transition-all duration-300 ${viewMode === 'card' ? 'bg-white dark:bg-slate-700 shadow-sm text-primary dark:text-white transform scale-100' : 'text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-200/50 dark:hover:bg-slate-700/50'}`}
                                >
                                    <LayoutGrid size={18} /> Grid View
                                </button>
                                <button 
                                    onClick={() => setViewMode('list')} 
                                    className={`flex items-center gap-2.5 px-6 py-2.5 rounded-lg text-sm font-bold transition-all duration-300 ${viewMode === 'list' ? 'bg-white dark:bg-slate-700 shadow-sm text-primary dark:text-white transform scale-100' : 'text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200 hover:bg-slate-200/50 dark:hover:bg-slate-700/50'}`}
                                >
                                    <List size={18} /> List View
                                </button>
                            </div>
                        </div>
                    </div>

                    {/* View Container */}
                    <div className="transition-all duration-500">
                        {viewMode === 'card' ? (
                            /* --- SCROLLER (CAROUSEL) VIEW --- */
                            <div className="flex overflow-x-auto gap-6 sm:gap-8 pb-12 snap-x snap-mandatory hide-scrollbar -mx-4 px-4 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                                {applications.map((app, index) => {
                                    const Icon = getCategoryIcon(app.category);
                                    
                                    const gradients = [
                                        'from-[#55a2d6] to-[#234b8c]', // Light Blue to Dark Blue
                                        'from-[#234b8c] to-[#eab344]', // Dark Blue to Yellow
                                        'from-[#eab344] to-[#b5be4c]', // Yellow to Olive
                                        'from-[#b5be4c] to-[#60af50]', // Olive to Green
                                        'from-[#60af50] to-[#35a796]', // Green to Teal
                                        'from-[#35a796] to-[#55a2d6]', // Teal to Light Blue
                                    ];
                                    const gradient = gradients[index % gradients.length];

                                    return (
                                        <article 
                                            key={app.id} 
                                            className={`shrink-0 w-[90vw] sm:w-[85vw] md:w-[80vw] lg:w-[80vw] xl:w-[80vw] snap-center rounded-[2.5rem] bg-gradient-to-br ${gradient} p-5 sm:p-8 shadow-2xl relative overflow-hidden group flex flex-col md:flex-row gap-6 sm:gap-8 border border-white/10`}
                                        >
                                            {/* Left/Top Content */}
                                            <div className="w-full md:w-[45%] flex flex-col z-10 text-white">
                                                <header className="mb-4 sm:mb-6">
                                                    <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white/10 backdrop-blur-sm border border-white/10 mb-4 sm:mb-6">
                                                        <Icon size={14} className="text-white/80" />
                                                        <span className="text-[10px] font-bold uppercase tracking-widest text-white/90">
                                                            {app.category}
                                                        </span>
                                                    </div>

                                                    <h2 className="text-2xl sm:text-3xl lg:text-4xl font-black mb-3 sm:mb-4 tracking-tight drop-shadow-md leading-[1.1]">
                                                        {app.title}
                                                    </h2>
                                                    <p className="text-white/70 text-xs sm:text-sm font-medium leading-relaxed mb-0 line-clamp-3">
                                                        {app.desc}
                                                    </p>
                                                </header>

                                                {/* Specs Grid */}
                                                <dl className="grid grid-cols-1 sm:grid-cols-2 gap-2 sm:gap-3 mt-auto pt-4 sm:pt-6 border-t border-white/10">
                                                    {Object.entries(app.specs).map(([key, val]) => {
                                                        if (key === 'compliance') return null;
                                                        return (
                                                            <div key={key} className="bg-black/20 backdrop-blur-md p-3 sm:p-4 rounded-xl border border-white/5 hover:bg-black/30 transition-colors">
                                                                <dt className="text-[8px] sm:text-[9px] uppercase tracking-widest font-bold text-white/50 mb-1">
                                                                    {key.replace(/_/g, ' ')}
                                                                </dt>
                                                                <dd className="text-[10px] sm:text-xs font-bold text-white leading-snug">
                                                                    {val}
                                                                </dd>
                                                            </div>
                                                        );
                                                    })}
                                                </dl>
                                            </div>

                                            {/* Right/Bottom Graphic Image */}
                                            <div className="w-full md:w-[55%] relative h-[220px] md:h-auto flex items-center justify-center z-10 mt-6 md:mt-0">
                                                <img 
                                                    src={app.image} 
                                                    alt={app.title} 
                                                    loading="lazy" 
                                                    className="absolute inset-0 w-full h-[120%] -top-[10%] object-cover rounded-2xl shadow-[0_20px_50px_rgba(0,0,0,0.5)] border border-white/20 transition-transform duration-700 ease-out group-hover:!transform-none" 
                                                    style={{ transform: 'perspective(1000px) rotateY(-12deg) scale(1.05)' }}
                                                />
                                                
                                                {/* Compliance Badge */}
                                                <div className="absolute -bottom-4 -right-4 md:bottom-4 md:right-4 bg-black/80 backdrop-blur-md px-3 sm:px-4 py-2 sm:py-2.5 rounded-full border border-white/10 flex items-center gap-2 shadow-2xl z-20 transition-transform duration-700 group-hover:-translate-y-2">
                                                    <CheckCircle2 size={14} className="text-green-400" />
                                                    <span className="text-[8px] sm:text-[10px] font-bold text-white/90 tracking-widest uppercase">
                                                        {app.specs.compliance}
                                                    </span>
                                                </div>
                                            </div>

                                            {/* Ambient Background Glows */}
                                            <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-white/5 rounded-full blur-[120px] pointer-events-none group-hover:bg-white/10 transition-colors duration-1000" />
                                            <div className="absolute bottom-0 left-0 w-[300px] h-[300px] bg-black/20 rounded-full blur-[80px] pointer-events-none" />
                                        </article>
                                    );
                                })}
                            </div>
                        ) : (
                            /* --- FULL-WIDTH LIST VIEW --- */
                            <div className="space-y-12 sm:space-y-16">
                                {applications.map((app, index) => {
                                    const Icon = getCategoryIcon(app.category);
                                    
                                    const gradients = [
                                        'from-[#55a2d6] to-[#234b8c]',
                                        'from-[#234b8c] to-[#eab344]',
                                        'from-[#eab344] to-[#b5be4c]',
                                        'from-[#b5be4c] to-[#60af50]',
                                        'from-[#60af50] to-[#35a796]',
                                        'from-[#35a796] to-[#55a2d6]',
                                    ];
                                    const gradient = gradients[index % gradients.length];

                                    return (
                                        <article key={app.id} className={`w-full flex flex-col lg:flex-row gap-8 lg:gap-12 items-stretch bg-gradient-to-br ${gradient} rounded-[2.5rem] p-6 sm:p-10 shadow-xl overflow-hidden relative group border border-white/10`}>
                                            
                                            {/* Image Side (Left) */}
                                            <div className="w-full lg:w-[45%] xl:w-[40%] relative z-10">
                                                <div className="relative h-[300px] lg:h-full lg:min-h-[400px] rounded-[1.5rem] overflow-hidden shadow-2xl border border-white/20">
                                                    <img 
                                                        src={app.image} 
                                                        alt={`Premium ${app.title} for BIPV architecture`} 
                                                        loading="lazy" 
                                                        className="absolute inset-0 w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105" 
                                                    />
                                                    <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent" />
                                                    
                                                    <div className="absolute top-6 left-6 z-20">
                                                        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-white/20 backdrop-blur-md border border-white/20 shadow-lg">
                                                            <Icon size={16} className="text-white" />
                                                            <span className="text-[10px] sm:text-xs font-black uppercase tracking-widest text-white">
                                                                {app.category}
                                                            </span>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>

                                            {/* Content Side (Right) */}
                                            <div className="w-full lg:w-[55%] xl:w-[60%] flex flex-col justify-center z-10 text-white">
                                                <header className="mb-8">
                                                    <h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white leading-[1.15] tracking-tight mb-4 drop-shadow-md">
                                                        {app.title}
                                                    </h2>
                                                    <p className="text-white/80 text-base sm:text-lg leading-relaxed font-medium">
                                                        {app.desc}
                                                    </p>
                                                </header>

                                                {/* Specs Semantic Grid */}
                                                <dl className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                                                    {Object.entries(app.specs).map(([key, val], i) => {
                                                        if (key === 'compliance') return null;
                                                        const isHighlight = i === 0;
                                                        return (
                                                            <div 
                                                                key={key} 
                                                                className={`p-4 sm:p-5 rounded-2xl border transition-all duration-300 ${
                                                                    isHighlight 
                                                                    ? 'bg-white/15 backdrop-blur-md border-white/30 shadow-lg transform group-hover:-translate-y-1' 
                                                                    : 'bg-black/10 backdrop-blur-sm border-white/10 hover:bg-black/20'
                                                                }`}
                                                            >
                                                                <dt className={`text-[10px] sm:text-xs uppercase tracking-widest font-black mb-2 ${isHighlight ? 'text-white' : 'text-white/60'}`}>
                                                                    {key.replace(/_/g, ' ')}
                                                                </dt>
                                                                <dd className="text-sm sm:text-base font-bold text-white leading-snug">
                                                                    {val}
                                                                </dd>
                                                            </div>
                                                        );
                                                    })}
                                                </dl>

                                                <div className="mt-8 pt-6 border-t border-white/10 flex items-center gap-3">
                                                    <CheckCircle2 size={20} className="text-green-400" />
                                                    <span className="text-xs sm:text-sm font-bold uppercase tracking-wider text-white/70">
                                                        Compliant with {app.specs.compliance}
                                                    </span>
                                                </div>
                                            </div>

                                            {/* Ambient Background Glows */}
                                            <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-white/5 rounded-full blur-[120px] pointer-events-none group-hover:bg-white/10 transition-colors duration-1000" />
                                        </article>
                                    );
                                })}
                            </div>
                        )}
                    </div>
                </div>
            </section>

            {/* Why Konara Section */}
            <WhyKonaraSection />
        </div>
    );
};

export default Products;
