import React, { useState, useEffect, useRef, useMemo } from 'react';
import {
    ArrowRight,
    Sparkles,
    Building2,
    Home,
    ShieldCheck,
    AppWindow,
    X,
    Award,
    Zap,
    Scale,
    Timer,
    CheckCircle2,
} from 'lucide-react';

const CATEGORIES = {
    'PV Glass': { label: 'PV Glass', icon: AppWindow },
    'Tiles': { label: 'Tiles', icon: Building2 },
    'Flex': { label: 'Flex', icon: Zap },
    'Solar Panels': { label: 'Solar Panels', icon: ShieldCheck },
};

const applications = [
    {
        id: 'Transparent',
        title: 'Transparent PV Glass',
        desc: 'Laminated glass that can generate energy and be used in fixed windows & facades. As the transparency of the glass goes higher, the power generated by it lowers.',
        image: '/images/transparent-pv-glass.jpg',
        category: 'PV Glass',
        yield: 92,
        specs: {
            Available_Technologies: 'Monocrystalline , CdTe',
            Customization_Options: 'Transparency, shape, size/dimensions, junction box placement, and colour tint can be customized as per requirements.',
            durability: 'High-Impact Safety Glass',
            warranty: '25 Years Power Output',
            compliance: 'IEC 61215, ISO 9001',
        }
    },
    {
        id: 'Opaque',
        title: 'Opaque PV Glass',
        desc: 'Rectangular opaque curtain wall glass that can generate energy. Can be customized with any color, texture/pattern, and custom image. Lighter colours decrease energy generation. Junction box & wiring can either go from the sides or from the back of the panels.',
        image: '/images/opaque-pv-glass.jpg',
        category: 'PV Glass',
        yield: 78,
        specs: {
            Available_Technologies: 'Monocrystalline',
            Customization_Options: 'Colour/pattern/image, junction box placement, shape & size can be customized as per requirements.',
            transmittance: 'Semi-Transparent (30%)',
            durability: 'Double Glazed Tempered',
            warranty: '20 Years Product Warranty',
            compliance: 'EN 12600 Safety Standard',
        }
    },
    {
        id: 'Crystalline',
        title: 'Crystalline PV Glass',
        desc: 'Monocrystalline PV square cells are integrated as a 2D grid & sandwiched between layers of glass. Transparency is changed by changing the number & size of the crystalline cells. Cells can be placed as per any custom pattern needed. Wires go from one side of the glass, and the wiring is hidden inside the frame.',
        image: '/images/crystalline-pv-glass.jpg',
        category: 'PV Glass',
        yield: 85,
        specs: {
            Available_Technologies: 'Monocrystalline',
            Customization_Options: 'Transparency, colour tint, and cell patterning can be customized as per requirements.',
            durability: 'Heat-Strengthened Laminated',
            warranty: '25 Years Performance',
            compliance: 'ASTM E2190 Insulating Glass',
        }
    },
    {
        id: 'PV Walkable',
        title: 'PV Walkable Tiles',
        desc: 'Bricks used for footpaths that can generate solar energy. Coefficient of friction depends on the micro-patterns developed on the front of the tile. Tiles are pasted on footpath bricks & the wiring goes from the back of the tiles.',
        image: '/images/pv-walkable-tiles-2.jpg',
        category: 'Tiles',
        yield: 65,
        specs: {
            Available_Technologies: 'Monocrystalline',
            Customization_Options: 'Size, shape, light transmission, weight, coefficient of friction, and colour/tint can be customized as per requirements.',
            durability: 'Safety Laminated Railing Grade',
            warranty: '15 Years Product Warranty',
            compliance: 'EN 12600 Impact Rating',
        }
    },
    {
        id: 'Thin-Film',
        title: 'Thin-Film PV Flex',
        desc: 'Solar flexes that can be mechanically incorporated on curved structures. This can be customized by size as per requirement.',
        image: '/images/thin-film-pv-flex.jpg',
        category: 'Flex',
        yield: 95,
        specs: {
            Available_Technologies: 'Thin-Film Flex',
            output: '210 W/m²',
            transmittance: 'Opaque Textured',
            durability: 'Class 4 Hail Impact Rated',
            warranty: '30 Years Linear Output',
            compliance: 'UL 1703 Fire Certified',
        }
    },
    {
        id: 'Solar Panels',
        title: 'Solar Panels',
        desc: 'Regular solar panels with a sturdy frame can be used as an opaque façade, curtain wall, or a spandrel. This can be customized by size as per requirement.',
        image: '/images/solar-panels.jpg',
        category: 'Solar Panels',
        yield: 70,
        specs: {
            Available_Technologies: 'Monocrystalline',
            output: '95 W/m²',
            transmittance: 'Clear Vision (45%)',
            durability: 'Sound Insulation Low-E Double Panel',
            warranty: '20 Years Structural Integrity',
            compliance: 'ASHRAE 90.1 Compliant',
        }
    },
];


const ImageGridSection = () => {
    const [activeFilter, setActiveFilter] = useState('all');
    const [selectedId, setSelectedId] = useState(null);
    const [isOpen, setIsOpen] = useState(false);
    const [renderDrawer, setRenderDrawer] = useState(false);
    const [visible, setVisible] = useState(false);

    const sectionRef = useRef(null);
    const drawerRef = useRef(null);

    const filtered = useMemo(
        () =>
            activeFilter === 'all'
                ? applications
                : applications.filter((a) => a.category === activeFilter),
        [activeFilter]
    );

    const selected = useMemo(
        () => applications.find((a) => a.id === selectedId) || null,
        [selectedId]
    );

    // Staggered intersection reveal
    useEffect(() => {
        const el = sectionRef.current;
        if (!el) return;
        const observer = new IntersectionObserver(
            ([entry]) => {
                if (entry.isIntersecting) {
                    setVisible(true);
                    observer.disconnect();
                }
            },
            { threshold: 0.1 }
        );
        observer.observe(el);
        return () => observer.disconnect();
    }, []);

    // Drawer entry/exit animation sequence
    useEffect(() => {
        if (selectedId) {
            setRenderDrawer(true);
            // Small tick to ensure element is in DOM before starting animation
            const timer = setTimeout(() => setIsOpen(true), 20);
            return () => clearTimeout(timer);
        } else {
            setIsOpen(false);
            const timer = setTimeout(() => setRenderDrawer(false), 400); // Match cubic-bezier slide duration
            return () => clearTimeout(timer);
        }
    }, [selectedId]);

    useEffect(() => {
        if (!selected) return;
        const onKey = (e) => {
            if (e.key === 'Escape') setSelectedId(null);
        };
        window.addEventListener('keydown', onKey);
        document.body.style.overflow = 'hidden';
        return () => {
            window.removeEventListener('keydown', onKey);
            document.body.style.overflow = '';
        };
    }, [selected]);

    // Helper for cards staggered entry transition
    const cardReveal = (index) => ({
        opacity: visible ? 1 : 0,
        transform: visible ? 'translateY(0)' : 'translateY(30px)',
        transitionProperty: 'opacity, transform',
        transitionDuration: '800ms',
        transitionTimingFunction: 'cubic-bezier(0.16, 1, 0.3, 1)',
        transitionDelay: visible ? `${index * 80}ms` : '0ms',
    });

    return (
        <section ref={sectionRef} className="py-12 sm:py-16 bg-background relative overflow-hidden transition-colors duration-500 border-y border-border">
            {/* Ambient Background Lights */}
            <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-secondary/5 dark:bg-secondary/15 rounded-full blur-[150px] pointer-events-none -translate-y-1/3 translate-x-1/3" />
            <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-primary/5 dark:bg-primary/10 rounded-full blur-[120px] pointer-events-none translate-y-1/3 -translate-x-1/3" />

            <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10 max-w-7xl">

                {/* Header (SEO Optimized) */}
                <header className="flex flex-col lg:flex-row lg:items-center justify-between gap-8 lg:gap-12 mb-10">
                    <div className="max-w-2xl">
                        <div className="inline-flex items-center gap-3 justify-center mb-5 px-4 py-1.5 rounded-full bg-secondary/10 dark:bg-secondary/20 border border-secondary/20 shadow-sm backdrop-blur-md">
                            <span className="w-2 h-2 rounded-full bg-secondary animate-pulse" />
                            <p className="text-secondary font-bold tracking-[0.15em] uppercase text-xs font-nav drop-shadow-sm">
                                Application Portfolio
                            </p>
                        </div>

                        <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-[3.5rem] font-black leading-[1.05] tracking-tight mb-2 drop-shadow-sm pb-2">
                            <span className="text-primary dark:text-white">Current Product </span>
                            <span className="text-secondary">Offerings</span>
                        </h2>
                        <span className="block mt-4 text-xl sm:text-2xl lg:text-3xl font-medium text-slate-500 dark:text-slate-400 leading-snug">
                            Glass That Generates Electricity Like <br className="hidden md:block" />
                            <span className="font-bold text-transparent bg-clip-text bg-gradient-to-r from-secondary to-orange-400 drop-shadow-sm">A Solar Panel.</span>
                        </span>
                    </div>
                    <div className="lg:max-w-[450px] lg:border-l-2 lg:border-secondary/30 lg:pl-6">
                        <p className="text-slate-600 dark:text-slate-400 text-base sm:text-lg leading-relaxed font-medium">
                            We offer a wide range of <strong>Building-Integrated Photovoltaic (BIPV)</strong> products designed to blend seamlessly into modern architecture. Our custom <strong>solar glass products</strong> are developed for high <strong>energy performance</strong>, architectural aesthetics, and complete design flexibility for scalable <strong>solar facades</strong>.
                        </p>
                    </div>
                </header>

                {/* Segmented Tab Filter Bar (Premium horizontal scroll on mobile) */}
                <div className="inline-flex overflow-x-auto p-1 rounded-full bg-slate-100/90 dark:bg-slate-800/80 border border-slate-200/80 dark:border-white/5 backdrop-blur-xl mb-10 w-fit max-w-full relative snap-x scrollbar-hide shadow-inner" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
                    <button
                        type="button"
                        onClick={() => setActiveFilter('all')}
                        className={`px-5 py-2 rounded-full text-[11px] font-bold uppercase tracking-wider transition-all duration-300 whitespace-nowrap shrink-0 snap-center ${activeFilter === 'all'
                            ? 'bg-white dark:bg-slate-900 text-secondary dark:text-blue-400 shadow-sm border border-slate-200/80 dark:border-white/10'
                            : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200/50 dark:hover:bg-white/5'
                            }`}
                    >
                        All Applications
                    </button>
                    {Object.entries(CATEGORIES).map(([key, cat]) => {
                        const Icon = cat.icon;
                        const isActive = activeFilter === key;
                        return (
                            <button
                                key={key}
                                type="button"
                                onClick={() => setActiveFilter(key)}
                                className={`inline-flex items-center gap-1.5 px-5 py-2 rounded-full text-[11px] font-bold uppercase tracking-wider transition-all duration-300 whitespace-nowrap shrink-0 snap-center ${isActive
                                    ? 'bg-white dark:bg-slate-900 text-secondary dark:text-blue-400 shadow-sm border border-slate-200/80 dark:border-white/10'
                                    : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200/50 dark:hover:bg-white/5'
                                    }`}
                            >
                                <Icon size={12} className={isActive ? 'text-secondary dark:text-blue-400' : 'text-slate-400 dark:text-slate-500'} />
                                {cat.label}
                            </button>
                        );
                    })}
                </div>

                {/* Grid - Cards layout */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 sm:gap-8">
                    {filtered.map((app, index) => {
                        const Icon = CATEGORIES[app.category].icon;
                        return (
                            <article
                                key={app.id}
                                style={cardReveal(index)}
                                className="flex flex-col flex-1"
                            >
                                <div
                                    className="group flex flex-col rounded-[2.5rem] overflow-hidden bg-white dark:bg-slate-900/40 backdrop-blur-xl border border-slate-200/50 dark:border-white/10 shadow-lg hover:shadow-2xl hover:shadow-secondary/30 hover:border-secondary/50 transform-gpu transition-all duration-700 ease-[cubic-bezier(0.25,1,0.5,1)] hover:-translate-y-3 flex-1 relative will-change-transform cursor-pointer"
                                    onClick={() => setSelectedId(app.id)}
                                >
                                    {/* Subtle inner glow on hover */}
                                    <div className="absolute inset-0 bg-gradient-to-b from-secondary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none z-20" />

                                    {/* Image Box */}
                                    <div className="relative aspect-[16/11] overflow-hidden bg-muted">
                                        <div className="absolute inset-0 bg-secondary/20 opacity-0 group-hover:opacity-100 transition-opacity duration-700 z-10 pointer-events-none mix-blend-overlay" />
                                        <div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 z-10 pointer-events-none" />

                                        <img
                                            src={app.image}
                                            alt={app.title}
                                            loading="lazy"
                                            className="w-full h-full object-cover transform-gpu transition-transform duration-1000 ease-[cubic-bezier(0.25,1,0.5,1)] group-hover:scale-[1.15] group-hover:rotate-1"
                                        />

                                        {/* Category tag */}
                                        <div className="absolute top-5 left-5 z-20">
                                            <span className="inline-flex items-center gap-1.5 px-4 py-2 rounded-full bg-white/95 dark:bg-slate-950/95 backdrop-blur-md border border-white/20 dark:border-white/10 text-[10px] font-bold uppercase tracking-wider text-primary dark:text-white shadow-md transform-gpu transition-transform duration-500 group-hover:scale-105">
                                                <Icon size={12} className="text-secondary" />
                                                {CATEGORIES[app.category].label}
                                            </span>
                                        </div>
                                    </div>

                                    {/* Content Box */}
                                    <div className="p-6 sm:p-8 flex flex-col flex-1 justify-between bg-white dark:bg-slate-900/40 relative z-20">
                                        <div>
                                            <div className="flex justify-between items-start gap-4 mb-4">
                                                <h3 className="text-xl sm:text-2xl font-black text-slate-900 dark:text-white tracking-tight leading-snug group-hover:text-secondary transition-colors duration-500">
                                                    {app.title}
                                                </h3>
                                            </div>
                                            <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed mb-6 line-clamp-2 group-hover:text-slate-800 dark:group-hover:text-slate-200 transition-colors duration-500">
                                                {app.desc}
                                            </p>
                                        </div>

                                        {/* Footer Specs highlight */}
                                        <div className="flex justify-between items-center pt-5 border-t border-slate-100 dark:border-white/5 transition-colors duration-500 group-hover:border-secondary/20">
                                            <div className="flex flex-col max-w-[60%]">
                                                {(() => {
                                                    const firstSpec = Object.entries(app.specs).find(([key]) => key !== 'compliance');
                                                    if (!firstSpec) return null;
                                                    return (
                                                        <>
                                                            <span className="text-[10px] text-slate-400 dark:text-slate-500 uppercase tracking-widest font-bold mb-1 truncate">
                                                                {firstSpec[0].replace(/_/g, ' ')}
                                                            </span>
                                                            <span className="text-sm font-black text-primary dark:text-white leading-tight line-clamp-1 group-hover:text-secondary transition-colors duration-500">
                                                                {firstSpec[1]}
                                                            </span>
                                                        </>
                                                    )
                                                })()}
                                            </div>
                                            <div className="w-10 h-10 rounded-full bg-slate-50 dark:bg-white/5 flex items-center justify-center text-slate-400 group-hover:bg-secondary group-hover:text-white group-hover:shadow-[0_0_15px_rgba(234,88,12,0.4)] transition-all duration-500">
                                                <ArrowRight size={16} className="group-hover:translate-x-0.5 transition-transform duration-300" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </article>
                        );
                    })}
                </div>

                {filtered.length === 0 && (
                    <p className="text-center text-slate-500 py-20 text-lg font-medium">
                        No applications in this category yet.
                    </p>
                )}
            </div>

            {/* Slide-over Drawer (Premium Drawer with smooth exit slide-out animations) */}
            {renderDrawer && selected && (
                <div className="fixed inset-0 z-50 overflow-hidden" role="dialog" aria-modal="true">
                    {/* Backdrop */}
                    <div
                        className={`absolute inset-0 bg-slate-950/60 backdrop-blur-sm transition-opacity duration-300 ${isOpen ? 'opacity-100' : 'opacity-0'}`}
                        onClick={() => setSelectedId(null)}
                    />

                    <div className="absolute inset-y-0 right-0 max-w-full flex pl-10">
                        {/* Drawer content */}
                        <div
                            className={`w-screen max-w-md sm:max-w-lg bg-white dark:bg-[#070e17] shadow-2xl border-l border-slate-200 dark:border-white/10 flex flex-col justify-between relative transform transition-transform duration-300 ease-out z-10 ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}
                        >
                            {/* Close Button */}
                            <button
                                type="button"
                                onClick={() => setSelectedId(null)}
                                className="absolute top-4 right-4 w-10 h-10 rounded-full bg-slate-900/50 hover:bg-slate-900/80 text-white flex items-center justify-center border border-white/20 hover:scale-105 transition-all duration-300 z-20"
                            >
                                <X size={18} />
                            </button>

                            {/* Header image cover */}
                            <div className="relative h-60 sm:h-72 overflow-hidden shrink-0 bg-slate-900">
                                <img
                                    src={selected.image}
                                    alt={selected.title}
                                    className="w-full h-full object-cover"
                                />
                                <div className="absolute inset-0 bg-gradient-to-t from-white dark:from-[#070e17] via-slate-950/20 to-transparent" />
                                <div className="absolute bottom-6 left-6 right-6">
                                    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-secondary text-white text-[10px] font-bold uppercase tracking-wider shadow-md mb-2.5">
                                        {React.createElement(CATEGORIES[selected.category].icon, { size: 12, className: "text-white" })}
                                        {CATEGORIES[selected.category].label}
                                    </span>
                                    <h3 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white tracking-tight drop-shadow-sm leading-tight">
                                        {selected.title}
                                    </h3>
                                </div>
                            </div>

                            {/* Specifications body list */}
                            <div className="flex-1 overflow-y-auto px-6 py-6 sm:px-8 space-y-6">
                                <div className="space-y-2">
                                    <h4 className="text-xs uppercase tracking-widest text-slate-400 dark:text-slate-500 font-bold">Product Description</h4>
                                    <p className="text-slate-600 dark:text-slate-300 text-sm sm:text-base leading-relaxed">
                                        {selected.desc}
                                    </p>
                                </div>

                                <div className="space-y-3">
                                    <h4 className="text-xs uppercase tracking-widest text-slate-400 dark:text-slate-500 font-bold">BIPV Tech Specifications</h4>
                                    <div className="grid grid-cols-1 gap-3">
                                        <div className="group/spec flex items-center justify-between p-4 rounded-2xl bg-slate-50 dark:bg-white/5 border border-slate-100 dark:border-white/5 hover:bg-white dark:hover:bg-white/10 hover:border-secondary/30 hover:shadow-md transition-all duration-300">
                                            <div className="flex items-center gap-3">
                                                <div className="w-8 h-8 rounded-full bg-white dark:bg-black/20 flex items-center justify-center shadow-sm group-hover/spec:scale-110 group-hover/spec:bg-secondary group-hover/spec:text-white transition-all duration-300">
                                                    <Zap className="text-secondary group-hover/spec:text-white transition-colors shrink-0" size={14} />
                                                </div>
                                                <span className="text-xs sm:text-sm font-bold text-slate-500 dark:text-slate-400 group-hover/spec:text-primary dark:group-hover/spec:text-white transition-colors">Yield Performance</span>
                                            </div>
                                            <span className="text-sm font-black text-primary dark:text-white group-hover/spec:text-secondary transition-colors">{selected.yield}% Rated</span>
                                        </div>

                                        {Object.entries(selected.specs).map(([key, value]) => {
                                            if (key === 'compliance') return null;

                                            // Assign a generic or specific icon based on key
                                            let Icon = AppWindow;
                                            if (key.toLowerCase().includes('durability')) Icon = ShieldCheck;
                                            else if (key.toLowerCase().includes('warranty')) Icon = Timer;
                                            else if (key.toLowerCase().includes('output') || key.toLowerCase().includes('technology')) Icon = Zap;
                                            else if (key.toLowerCase().includes('custom')) Icon = AppWindow;
                                            else if (key.toLowerCase().includes('transmittance')) Icon = Scale;

                                            return (
                                                <div key={key} className="group/spec flex items-center justify-between p-4 rounded-2xl bg-slate-50 dark:bg-white/5 border border-slate-100 dark:border-white/5 hover:bg-white dark:hover:bg-white/10 hover:border-secondary/30 hover:shadow-md transition-all duration-300">
                                                    <div className="flex items-center gap-3 max-w-[45%]">
                                                        <div className="w-8 h-8 rounded-full bg-white dark:bg-black/20 flex items-center justify-center shadow-sm group-hover/spec:scale-110 group-hover/spec:bg-secondary group-hover/spec:text-white transition-all duration-300">
                                                            <Icon className="text-secondary group-hover/spec:text-white transition-colors shrink-0" size={14} />
                                                        </div>
                                                        <span className="text-xs sm:text-sm font-bold text-slate-500 dark:text-slate-400 capitalize group-hover/spec:text-primary dark:group-hover/spec:text-white transition-colors">
                                                            {key.replace(/_/g, ' ')}
                                                        </span>
                                                    </div>
                                                    <span className="text-sm font-black text-primary dark:text-white text-right max-w-[50%] leading-tight group-hover/spec:text-secondary transition-colors">
                                                        {value}
                                                    </span>
                                                </div>
                                            );
                                        })}
                                    </div>
                                </div>
                            </div>

                            {/* Action footer */}
                            <div className="p-5 border-t border-slate-100 dark:border-white/5 bg-slate-50 dark:bg-slate-900/30 flex items-center justify-between gap-4 shrink-0">
                                <div className="flex items-center gap-2">
                                    <CheckCircle2 className="text-secondary shrink-0" size={18} />
                                    <span className="text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">{selected.specs.compliance}</span>
                                </div>
                                <button
                                    type="button"
                                    onClick={() => setSelectedId(null)}
                                    className="bg-primary hover:bg-primary/95 text-white dark:bg-secondary dark:hover:bg-secondary/95 px-6 py-3 rounded-full text-xs font-bold uppercase tracking-widest shadow-md transition-all duration-300"
                                >
                                    Dismiss Specs
                                </button>
                            </div>

                        </div>
                    </div>
                </div>
            )}
        </section>
    );
};

export default ImageGridSection;